  version: "3.8"

  services:
    database:
      image: postgres:14
      container_name: postgres_db
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: product_db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    backend:
      build: .
      volumes:
        - .:/app
      container_name: fastapi_backend
      restart: always
      depends_on:
        - database
      environment:
        DATABASE_URL: postgresql://admin:admin@database:5432/product_db
        OPENAI_API_KEY: ${OPENAI_API_KEY} 
      ports:
        - "8000:8000"

    adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"

  volumes:
    postgres_data:
